apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: magtape-pdb
  namespace: magtape-system
  labels:
    app: magtape
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: magtape