name: image-build

on:
  release:
    # Dynamic releasetag tag is set based on the assumption this ci task only runs on release
    types: [published]

# Variables to be used throughout the workflow manifest
env:
  TARGET_PLATFORMS: linux/amd64,linux/arm64,linux/ppc64le

jobs:

  # Build and push magtape-init container image
  build-magtape-init-image:
    name: Build and push magtape-init images to DockerHub
    runs-on: ubuntu-latest

    steps:
      
      - name: Check out the repo
        uses: actions/checkout@v2

      # Collect Release Tag is used to to collect information needed later in the action and expose it so it can be referenced
      - name: Collect Release Tag
        id: prep
        # GITHUB_REF variable must exist in action; this may rely on {{ on: release: types: [published] }} gating the action
        run: |
          echo ::set-output name=releasetag::${GITHUB_REF#refs/tags/}

      # Setup QEMU to support multi-arch builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
          
      # Part of docker/build-push-action@v2; setting up the build system
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      # Part of docker/build-push-action@v2; login to dockerhub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push magtape-init image to DockerHub
        if: github.repository == 'tmobile/magtape'
        timeout-minutes: 30
        uses: docker/build-push-action@v2
        with:
          context: ./app/magtape-init/
          # file should be specified relative to the repo root rather than relative to the context
          file: ./app/magtape-init/Dockerfile
          # Defines the target platform architectures images should be built for
          platforms: ${{ env.TARGET_PLATFORMS }}
          # push is no longer defaulted to true under v2; to push you must specify push is true
          push: true
          # Uses the releasetag output exposed by the Collect Release Tag step to set the tag under v2
          tags: tmobile/magtape-init:${{ steps.prep.outputs.releasetag }},tmobile/magtape-init:latest

  # Build and push magtape container image
  build-magtape-image:
    name: Build and push magtape images to DockerHub
    runs-on: ubuntu-latest

    steps:

      - name: Check out the repo
        uses: actions/checkout@v2

      # Collect Release Tag is used to to collect information needed later in the action and expose it so it can be referenced
      - name: Collect Release Tag
        id: prep
        # GITHUB_REF variable must exist in action; this may rely on {{ on: release: types: [published] }} gating the action
        run: |
          echo ::set-output name=releasetag::${GITHUB_REF#refs/tags/}

      # Setup QEMU to support multi-arch builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # Part of docker/build-push-action@v2; setting up the build system
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Part of docker/build-push-action@v2; login to dockerhub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push magtape image to DockerHub
        if: github.repository == 'tmobile/magtape'
        timeout-minutes: 30
        uses: docker/build-push-action@v2
        with:
          context: ./app/magtape/
          # file should be specified relative to the repo root rather than relative to the context
          file: ./app/magtape/Dockerfile
          # Defines the target platform architectures images should be built for
          platforms: ${{ env.TARGET_PLATFORMS }}
          # push is no longer defaulted to true under v2; to push you must specify push is true
          push: true
          # Uses the releasetag output exposed by the Collect Release Tag step to set the tag under v2
          tags: tmobile/magtape:${{ steps.prep.outputs.releasetag }},tmobile/magtape:latest
