name: rego-checks

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

# Jobs
jobs:
  # Job to lint code
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        opa-version:
          - v0.37.2

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      timeout-minutes: 5
      run: |
        mkdir -p "${GITHUB_WORKSPACE}/bin"
        curl -L -o "${GITHUB_WORKSPACE}/bin/opa" https://openpolicyagent.org/downloads/${{ matrix.opa-version }}/opa_linux_amd64
        chmod +x "${GITHUB_WORKSPACE}/bin/opa"
        echo "${GITHUB_WORKSPACE}/bin" >> $GITHUB_PATH

    - name: Lint
      timeout-minutes: 5
      run: |
        make ci-lint-rego
  
  # Job to execute unit tests
  unit-test:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        opa-version:
          - v0.37.2

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      timeout-minutes: 5
      run: |
        mkdir -p "${GITHUB_WORKSPACE}/bin"
        curl -L -o "${GITHUB_WORKSPACE}/bin/opa" https://openpolicyagent.org/downloads/${{ matrix.opa-version }}/opa_linux_amd64
        chmod +x "${GITHUB_WORKSPACE}/bin/opa"
        echo "${GITHUB_WORKSPACE}/bin" >> $GITHUB_PATH

    - name: Execute Unit Tests
      timeout-minutes: 5
      run: |
        make test-rego
